apiVersion: v2
description: Helm Chart for Docker Samples example-voting-app
name: example-voting-app
keywords:
  - codefresh
  - kubernetes
  - example-voting-app
sources:
  - https://github.com/aperture-sci/example-voting-app
maintainers:
  - name: Dustin Van Buskirk
    email: dustin@codefresh.io
dependencies:
  - name: example-voting-app
    version: 1.1.56
    repository: file://../../