apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eva-staging
  annotations:
    codefresh.io/product: example-voting-app
spec:
  project: default
  source:
    repoURL: https://github.com/salesdemocf/poc-demo-1-demo-app.git
    targetRevision: HEAD
    path: environments/staging
  destination:
    namespace: staging
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
