apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eva-production
  annotations:
    codefresh.io/product: example-voting-app
spec:
  project: default
  source:
    repoURL: https://github.com/salesdemocf/poc-demo-1-demo-app.git
    targetRevision: HEAD
    path: environments/production
    plugin:
      name: argocd-vault-plugin-helm
      env:
        - name: HELM_ARGS
          value: -f values.yaml
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
